// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: booking.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookingService_AddAvailability_FullMethodName    = "/pbB.BookingService/AddAvailability"
	BookingService_ViewAvailability_FullMethodName   = "/pbB.BookingService/ViewAvailability"
	BookingService_EditAvailability_FullMethodName   = "/pbB.BookingService/EditAvailability"
	BookingService_RemoveAvailability_FullMethodName = "/pbB.BookingService/RemoveAvailability"
	BookingService_AddBooking_FullMethodName         = "/pbB.BookingService/AddBooking"
	BookingService_ViewBooking_FullMethodName        = "/pbB.BookingService/ViewBooking"
	BookingService_AddPrescription_FullMethodName    = "/pbB.BookingService/AddPrescription"
)

// BookingServiceClient is the client API for BookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingServiceClient interface {
	AddAvailability(ctx context.Context, in *Availability, opts ...grpc.CallOption) (*Response, error)
	ViewAvailability(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*AvailabilityListResponse, error)
	EditAvailability(ctx context.Context, in *Availability, opts ...grpc.CallOption) (*Response, error)
	RemoveAvailability(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Response, error)
	AddBooking(ctx context.Context, in *Booking, opts ...grpc.CallOption) (*Response, error)
	ViewBooking(ctx context.Context, in *ID, opts ...grpc.CallOption) (*BookingListResponse, error)
	AddPrescription(ctx context.Context, in *Prescription, opts ...grpc.CallOption) (*Response, error)
}

type bookingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingServiceClient(cc grpc.ClientConnInterface) BookingServiceClient {
	return &bookingServiceClient{cc}
}

func (c *bookingServiceClient) AddAvailability(ctx context.Context, in *Availability, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BookingService_AddAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) ViewAvailability(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*AvailabilityListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityListResponse)
	err := c.cc.Invoke(ctx, BookingService_ViewAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) EditAvailability(ctx context.Context, in *Availability, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BookingService_EditAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) RemoveAvailability(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BookingService_RemoveAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) AddBooking(ctx context.Context, in *Booking, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BookingService_AddBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) ViewBooking(ctx context.Context, in *ID, opts ...grpc.CallOption) (*BookingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingListResponse)
	err := c.cc.Invoke(ctx, BookingService_ViewBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) AddPrescription(ctx context.Context, in *Prescription, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BookingService_AddPrescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServiceServer is the server API for BookingService service.
// All implementations must embed UnimplementedBookingServiceServer
// for forward compatibility.
type BookingServiceServer interface {
	AddAvailability(context.Context, *Availability) (*Response, error)
	ViewAvailability(context.Context, *NoParam) (*AvailabilityListResponse, error)
	EditAvailability(context.Context, *Availability) (*Response, error)
	RemoveAvailability(context.Context, *ID) (*Response, error)
	AddBooking(context.Context, *Booking) (*Response, error)
	ViewBooking(context.Context, *ID) (*BookingListResponse, error)
	AddPrescription(context.Context, *Prescription) (*Response, error)
	mustEmbedUnimplementedBookingServiceServer()
}

// UnimplementedBookingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookingServiceServer struct{}

func (UnimplementedBookingServiceServer) AddAvailability(context.Context, *Availability) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAvailability not implemented")
}
func (UnimplementedBookingServiceServer) ViewAvailability(context.Context, *NoParam) (*AvailabilityListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewAvailability not implemented")
}
func (UnimplementedBookingServiceServer) EditAvailability(context.Context, *Availability) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditAvailability not implemented")
}
func (UnimplementedBookingServiceServer) RemoveAvailability(context.Context, *ID) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAvailability not implemented")
}
func (UnimplementedBookingServiceServer) AddBooking(context.Context, *Booking) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBooking not implemented")
}
func (UnimplementedBookingServiceServer) ViewBooking(context.Context, *ID) (*BookingListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewBooking not implemented")
}
func (UnimplementedBookingServiceServer) AddPrescription(context.Context, *Prescription) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPrescription not implemented")
}
func (UnimplementedBookingServiceServer) mustEmbedUnimplementedBookingServiceServer() {}
func (UnimplementedBookingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBookingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingServiceServer will
// result in compilation errors.
type UnsafeBookingServiceServer interface {
	mustEmbedUnimplementedBookingServiceServer()
}

func RegisterBookingServiceServer(s grpc.ServiceRegistrar, srv BookingServiceServer) {
	// If the following call pancis, it indicates UnimplementedBookingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookingService_ServiceDesc, srv)
}

func _BookingService_AddAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Availability)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).AddAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_AddAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).AddAvailability(ctx, req.(*Availability))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_ViewAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).ViewAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_ViewAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).ViewAvailability(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_EditAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Availability)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).EditAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_EditAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).EditAvailability(ctx, req.(*Availability))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_RemoveAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).RemoveAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_RemoveAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).RemoveAvailability(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_AddBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Booking)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).AddBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_AddBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).AddBooking(ctx, req.(*Booking))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_ViewBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).ViewBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_ViewBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).ViewBooking(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_AddPrescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Prescription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).AddPrescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingService_AddPrescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).AddPrescription(ctx, req.(*Prescription))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingService_ServiceDesc is the grpc.ServiceDesc for BookingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbB.BookingService",
	HandlerType: (*BookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAvailability",
			Handler:    _BookingService_AddAvailability_Handler,
		},
		{
			MethodName: "ViewAvailability",
			Handler:    _BookingService_ViewAvailability_Handler,
		},
		{
			MethodName: "EditAvailability",
			Handler:    _BookingService_EditAvailability_Handler,
		},
		{
			MethodName: "RemoveAvailability",
			Handler:    _BookingService_RemoveAvailability_Handler,
		},
		{
			MethodName: "AddBooking",
			Handler:    _BookingService_AddBooking_Handler,
		},
		{
			MethodName: "ViewBooking",
			Handler:    _BookingService_ViewBooking_Handler,
		},
		{
			MethodName: "AddPrescription",
			Handler:    _BookingService_AddPrescription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booking.proto",
}
